# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.pgManager.limit : 3
    img_upload_directory : %kernel.root_dir%/../web/images

services:
     app.dbManager:
            class: AppBundle\Services\DataBaseManager
            arguments: ["@doctrine.orm.entity_manager"]
     app.pgManager:
            class: AppBundle\Services\PaginateManager
            arguments: ['%app.pgManager.limit%']
     app.data_base_subscriber:
             class: AppBundle\EventListener\DataBaseSubscriber
             arguments: ['@security.password_encoder']
             tags:
                  - { name: doctrine.event_subscriber }
     app.user_locale_listener:
             class: AppBundle\EventListener\LanguageListener
             arguments: ['@session']
             tags:
                 - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
     app.locale_listener:
             class: AppBundle\EventListener\LocaleListener
             arguments: ['%kernel.default_locale%']
             tags:
                 - { name: kernel.event_subscriber }

